#### To generate a sequence of non-random values using NumPy, you can use the `arange` function. The name "arange" stands for "array range." It is similar to Python's built-in `range` function, but with a key difference: while `range` returns a Python object, `arange` generates a NumPy array.

#### The `arange` function creates a sequence of integer values within a specified range, making it a versatile tool for numerical computations.


In [97]:
# using python's built in range fn
list(range(27))

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26]

In [98]:
import numpy as np

In [99]:
#using arange() fn of numpy.
array_range = np.arange(10)
#note: array value starts from 0 only.
array_range

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### arange takes upto 4 arguments. start, stop, step and datatype.
#### start: starting point of array
#### stop: ending point
#### step: jump between values
#### dtype: datatype

####  when a stop argument is not provided, the function assumes that stop=start and switches the origin to 0 but if you provide only stop argument, it will throw exception.


In [100]:
# this works in newer versions of numpy
array_range1=np.arange(stop=14)
array_range1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [101]:
array_range2=np.arange(start=0,stop=30,step=4,dtype=float)
array_range2

array([ 0.,  4.,  8., 12., 16., 20., 24., 28.])

In [102]:
array_range3 = np.arange(start=0, stop=30, step=2.5, dtype=np.int32)
#### Since 30 ÷ 2.5 = 12, this results in 12 original steps up to 30. However, because dtype=np.int32 is specified, the function assumes you want integer values only. It truncates the values to integers and returns the first 12 values within that range.
array_range3

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22], dtype=int32)