In [17]:
#to provide operation on dissimilar arrays in numpy, broadcasting is used.

# Broadcasting In Numpy

 - The main idea is simple: the smaller array is stretched (broadcasted) to match the shape of the larger array so operations can work. If it’s not possible to stretch the smaller array, you’ll get a broadcasting error.

- The best way to get good at broadcasting is by practicing a lot, imagining and building intuition over time.

## but if one still persists to learn broadcasting rules:

For broadcasting to work, NumPy applies these rules to align the shapes of the arrays:

- Right Alignment: Starting from the trailing dimensions, NumPy compares each dimension of the arrays.
- Matching Dimensions:
If two dimensions are the same, they are compatible.
If one of the dimensions is 1, it is stretched to match the other dimension.
If the dimensions are different and none of them is 1, broadcasting fails, and a ValueError is raised.
- Adding New Dimensions: If one array has fewer dimensions than the other, new axes (of size 1) are added to the left of the smaller array's shape.


In [18]:
import numpy as np

In [19]:
#Broadcasting rules
# 1. Shapes Need to Match
# To do operations between two arrays, their shapes need to be the same.
# If they’re not the same, NumPy tries to make them match using broadcasting.

# 2. Broadcasting Adjustments
# For broadcasting to work:
# - If a dimension is the same: Cool, no problem!
# - If a dimension is 1: It’s stretched to match the other dimension.
# - If dimensions are different and not 1: Sorry, broadcasting fails.

# 3. Add Missing Dimensions
# If one array has fewer dimensions, NumPy pretends it has extra dimensions
# (with size 1) at the front to match the other array’s shape.

# When Does Broadcasting Fail?
# Broadcasting fails when two dimensions:
# - Are different, and
# - Neither is 1.

# If this happens, you’ll see an error.

# Examples (Super Simple)

# Example 1: It Works
arr1 = np.array([1, 2, 3])  # Shape: (3,)
arr2 = np.array([[10], [20], [30]])  # Shape: (3, 1)

result = arr1 + arr2  # Shape: (3, 3)
print("Example 1 - Broadcasting Works:")
print(result)
# Output:
# [[11 12 13]
#  [21 22 23]
#  [31 32 33]]

# Why does it work?
# - `arr1` is stretched to `(1, 3)` and `arr2` is stretched to `(3, 1)`.

# Example 2: It Fails
arr1 = np.array([1, 2, 3])  # Shape: (3,)
arr2 = np.array([4, 5, 6, 7])  # Shape: (4,)

try:
    result = arr1 + arr2
except ValueError as e:
    print("\nExample 2 - Broadcasting Fails:")
    print(e)
# Error: Shapes (3,) and (4,) don’t match!

# Example 3: Scalars Always Work
arr1 = np.array([[1, 2], [3, 4]])  # Shape: (2, 2)
scalar = 10  # Shape: ()

result = arr1 + scalar  # Shape: (2, 2)
print("\nExample 3 - Scalars Always Work:")
print(result)
# Output:
# [[11 12]
#  [13 14]]

# Why does it work?
# Scalars automatically stretch to match any array.

# Remember This:
# 1. If the shapes don’t match: NumPy tries to stretch dimensions with 1.
# 2. If stretching works: Great! Operations proceed.
# 3. If stretching doesn’t work: Error.

# Just think of it like matching shapes and stretching smaller ones.
# If it makes sense, NumPy will do it for you!

Example 1 - Broadcasting Works:
[[11 12 13]
 [21 22 23]
 [31 32 33]]

Example 2 - Broadcasting Fails:
operands could not be broadcast together with shapes (3,) (4,) 

Example 3 - Scalars Always Work:
[[11 12]
 [13 14]]


In [20]:
#example-4
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6,7,8])
arr1+arr2

ValueError: operands could not be broadcast together with shapes (3,) (5,) 

In [4]:
#same dimension broadcasting-1d
#example-5
arr1=np.array([1, 2, 3])
arr2=np.array([4])
arr1+arr2
# what numpy does: the second array i.e, arr2 which is a 1*1 array is broadcast into a 1*3 array and then addition operation is happening.

array([5, 6, 7])

In [2]:
#different dimension broadcasting-as arr1 is 2d array and arr2 is one d array
#example-6
arr1=np.array([[1, 2, 3],[4,5,6]])
print(arr1.ndim)
arr2=np.array([2,2,2])
print(arr2.ndim)
arr1+arr2
# here the arr2 is broadcast by numpy from a 1*3 to 2*3 array.

2
1


array([[3, 4, 5],
       [6, 7, 8]])

In [12]:
#example-7
arr1=np.array([[1, 2],[3,4],[5,6]])
arr2=np.array([[2],[4],[6]])
# first array is of dimension 3*2 and second one is of 3*1, so second is broadcast to match the first array dimension. so, arr2   became [[2,2],[4,4],[6,6]] and arr1 is [[1, 2],[3,4],[5,6]].
# now addition is possible as both array dimensions are 3*2.
arr1+arr2

array([[ 3,  4],
       [ 7,  8],
       [11, 12]])

In [15]:
#example-8
arr1=np.array([[1, 2],[3,4],[5,6]]) #3*2 dimension
arr2=np.array([2,2,2]) #1*3 dimension
arr1+arr2

# no chance that a 1*3 array could be ever broadcast to 3*2 array. that's why this error arises.

ValueError: operands could not be broadcast together with shapes (3,2) (3,) 

In [34]:
#example-9
arr1=np.array([[1, 2],[3,4],[5,6]])
arr2=np.array([[2,2],[3,4],[5,6],[7,8]])
arr1+arr2

# Reason for Failure
# Shape of arr1: (3, 2)
# This means arr1 has 3 rows and 2 columns.
#
# Shape of arr2: (4, 2)
# This means arr2 has 4 rows and 2 columns.
#
# Broadcasting Rules:
# For broadcasting to work, NumPy compares the dimensions of the arrays from right to left:
#
# The dimensions must either match exactly, or
# One of the dimensions must be 1 (so it can be stretched to match the other).
# Here's the comparison of dimensions:
#
# The last dimensions (number of columns): 2 (both arrays) → Compatible.
# The second-to-last dimensions (number of rows): 3 vs 4 → Not compatible, and neither is 1.
# Because the number of rows (3 vs 4) is incompatible, broadcasting cannot occur, and NumPy raises a ValueError:

ValueError: operands could not be broadcast together with shapes (3,2) (4,2) 