In [5]:
import numpy as np

In [56]:
#np.empty()
#creates an "empty" n-d array
#runs an array without initializing entries
#fastest way to generate n-d array
array_empty=np.empty(shape=(3,4))
array_empty

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

### `np.empty()` is fast because it doesn't initialize the array with specific values (like zeros or ones). Instead, it allocates memory without setting the values, meaning the array may contain random data from the previous contents of that memory. This approach improves efficiency, but it also means the array doesn't have consistent data, which can be risky if you don't overwrite it immediately. Essentially, it reuses memory without creating new data.

In [57]:
#np.zeros()
#np.zeros() creates an array full of zeros
#the only difference between np.zeros() and np.empty() will be that the output will always be zero (consistent) for np.zeros()
#default

array_zeros=np.zeros((3,4))



In [58]:
array_zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [59]:
array_zeros=np.zeros((3,4),dtype=int)

In [60]:
array_zeros

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [61]:

#np.ones() -similar to np.zeros . just in place of 0 it becomes 1

In [62]:
array_ones=np.ones((3,4),dtype=int)
array_ones

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [63]:
#np.full()- generates an array filled entirely with a specific value
#contains an additional mandatory argument called value. In the below example it is 5.
#takes scalar values as mandatory arguments(here scalar refers to single individual values)
array_full=np.full((3,4),5)
array_full

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])