In [34]:
# Different ways of generating data: new methods we can use to generate integers and probabilities
import numpy as np
from numpy.random import Generator as gen
from numpy.random import PCG64 as pcg

In [35]:
array_rg=gen(pcg(seed=128))

In [36]:
# integers()- generates whole numbers. this method requires defining a fixed range of values to choose from.

# if we only provides a single value, it automatically assumes we only want integers between 0 and the value itself.
array_rg.integers(6,size=(4,4))

array([[4, 3, 4, 2],
       [5, 2, 0, 2],
       [2, 0, 1, 3],
       [1, 5, 0, 5]])

In [37]:
array_rg.integers(low=20,high=40,size=(4,4))

array([[38, 30, 39, 28],
       [21, 37, 34, 26],
       [27, 36, 29, 33],
       [28, 22, 34, 25]])

In [38]:
#random() method
# the random method is not compatible between 0 and 1 since probabilities are always between 0 and 1.
array_rg.random(size=(4,4))

array([[0.97822197, 0.04673085, 0.31142437, 0.02422937],
       [0.99297125, 0.96616327, 0.53723508, 0.98905943],
       [0.29361544, 0.05936836, 0.58052105, 0.24448327],
       [0.37632227, 0.3844723 , 0.92544899, 0.76470818]])

In [39]:
#The choice() method is used to randomly select an element from a given sequence, such as a list, array, or tuple, mimicking the process of making an arbitrary choice.
#It also allows specifying the probabilities associated with each element, enabling more control over the random selection process.

#Probability Weights: You can assign probabilities to each element, determining how likely it is to be chosen. If not specified, all elements are equally likely to be selected.

array_rg.choice([4,6,8,9,10],size=(4,4))
# this time all the elements of the array comes from the choice we had provided earlier i.e, [4,6,8,9,10]


array([[ 9,  4,  9, 10],
       [ 9, 10,  6,  4],
       [ 8,  6,  6,  8],
       [ 9,  4, 10,  4]])

In [40]:

choices = [1, 2, 3, 4]
result = array_rg.choice(choices, size=(5,5))
result
# Each element has a 25% chance of being selected.


array([[3, 3, 4, 1, 3],
       [4, 3, 1, 1, 3],
       [3, 3, 1, 3, 4],
       [4, 1, 1, 2, 3],
       [4, 3, 1, 3, 3]])

In [41]:
#example for probability weights-specifying the probability weights
choices = ['A', 'B', 'C']
probabilities = [0.1, 0.7, 0.2]  # B is most likely to be chosen as more probability weight is assigned.
# note sum of all probability weights equals to 1.
result = array_rg.choice(choices, size=(5,5), p=probabilities)
result


array([['B', 'B', 'B', 'B', 'C'],
       ['B', 'B', 'B', 'B', 'B'],
       ['B', 'B', 'A', 'A', 'C'],
       ['C', 'B', 'A', 'C', 'B'],
       ['B', 'B', 'B', 'B', 'B']], dtype='<U1')