# Mathematical Operations in Numpy

In [106]:
import numpy as np
from numpy import dtype

## Element-wise Operations

In [107]:
#Element-wise Addition
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
addition_result = a + b
addition_result


array([5, 7, 9])

In [108]:
# Element-wise Subtraction
subtraction_result = a - b
subtraction_result

array([-3, -3, -3])

In [109]:
#  Element-wise Multiplication
multiplication_result = a * b
multiplication_result

array([ 4, 10, 18])

In [110]:
#  Element-wise Division
division_result = a / b
division_result

array([0.25, 0.4 , 0.5 ])

In [111]:
# Element-wise Exponentiation
exponentiation_result = a ** 2
exponentiation_result

array([1, 4, 9])

## Universal Functions (ufuncs)
### 
### Radians and degrees are two units used to measure angles.

### Degrees:

#### A circle is divided into 360 equal parts, and each part is called a degree (°). So, one complete revolution around a circle is 360°.

### Radians:

#### A radian is based on the radius of a circle. It is the angle subtended by an arc whose length is equal to the radius of the circle. 
### There are 2π radians in a complete revolution around a circle.


## pi=180 degrees

### 1. Sine Function

In [112]:
# Sine Function
angles = np.array([0, np.pi/2, np.pi])
sine_result = np.sin(angles)
sine_result


array([0.0000000e+00, 1.0000000e+00, 1.2246468e-16])

### 2.Cos Function

In [113]:
#Cosine Function
cosine_result = np.cos(angles)
cosine_result


array([ 1.000000e+00,  6.123234e-17, -1.000000e+00])

### 3. Exponential Function
#### The exponential function is $e^x$, where e is Euler's number (approximately 2.71828), and x is the element of the array.

In [114]:
# Exponential Function
# numpy array a is defined at the start of this jupyter notebook.
exponential_result = np.exp(a)
exponential_result


array([ 2.71828183,  7.3890561 , 20.08553692])

### 4. Logarithm Function  np.log() function:
#### np.log() calculates the natural logarithm (logarithm base e) of each element in the input array. The natural logarithm of a number x is written as ln(x), and it is the inverse of the exponential function $𝑒^x$ .The logarithm of x, where 𝑥=0, is undefined because the natural logarithm of zero approaches negative infinity.

In [115]:
#Logarithm Function
logarithm_result = np.log(a)  # you can add 1 to each element using a+1 to avoid log(0)
logarithm_result


array([0.        , 0.69314718, 1.09861229])

## Linear Algebra Functions



### 1. Dot Product

#### np.dot(a, b) computes the dot product of arrays a and b.
#### If a and b are both 1D arrays, it performs the traditional dot product of vectors.
#### If a and b are both 2D arrays, it performs matrix multiplication.

In [116]:
#  Dot Product
dot_product_result = np.dot(a, b)
dot_product_result


np.int64(32)

### 2. Matrix Inversion

In [117]:
#  Matrix Inversion
matrix = np.array([[1, 2], [3, 4]])
inverse_result = np.linalg.inv(matrix)
inverse_result


array([[-2. ,  1. ],
       [ 1.5, -0.5]])

### 3. Solving Linear Equations with `np.linalg.solve` in NumPy

When working with systems of linear equations in Python, `np.linalg.solve` is your go-to function for finding solutions efficiently. It is designed to solve equations of the form:

\[
Ax = B
\]

Where:
- **A**: is the coefficient matrix (square and invertible).
- **B**: is a vector or matrix representing known values.
- **x**: is the unknown variable vector that you're solving for.


Instead of manually computing the inverse of a matrix (which can be computationally expensive and numerically unstable), `np.linalg.solve` solves the system directly, providing a faster and more accurate solution.
 
A: The coefficient matrix (must be square).If A is not invertible, np.linalg.solve will throw a LinAlgError, indicating that the matrix is singular.

B: The dependent variable values (a vector or matrix)

### Syntax

```python
np.linalg.solve(A, B)




In [118]:
#np.linalg.solve()
import numpy as np

# Coefficient matrix A and constant matrix B
A = np.array([[2, 3], [1, -4]])
B = np.array([8, -2])

# Solving for x
x = np.linalg.solve(A, B)
print(x)  # Output: [x_value, y_value]



[2.36363636 1.09090909]


# Statistical Functions

### 1. `np.mean()`

This function computes the average of all the elements in the array. The arithmetic mean is the sum of the elements divided by the number of elements.


In [119]:
arr = np.array([1, 2, 3, 4, 5])
mean_value = np.mean(arr)
mean_value  # Output: 3.0

np.float64(3.0)

### `np.mean()` for 2D Arrays
In a 2D array, `np.mean()` can compute:

1. The overall mean of all elements in the array.
2. The mean along a specified axis:
   - **axis=0**: Calculates the mean along each column.
   - **axis=1**: Calculates the mean along each row.

Using `axis` makes it easy to get the mean of rows or columns in matrices.


In [120]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
overall_mean = np.mean(arr_2d)
overall_mean  # Output: 5.0


np.float64(5.0)

### 2. `np.median()`
The `np.median()` function finds the median, which is the middle value of the array when sorted. If the array has an even number of elements, it returns the average of the two middle values.


In [121]:
arr = np.array([1, 3, 3, 6, 7, 8, 9])
median_value = np.median(arr)
median_value  # Output: 6.0


np.float64(6.0)

### `np.median()` for 2D Arrays
For a 2D array, `np.median()` can calculate:

1. The median of all elements in the array.
2. The median along a specific axis:
   - **axis=0**: Calculates the median for each column.
   - **axis=1**: Calculates the median for each row.


In [122]:
overall_median = np.median(arr_2d,axis=1)
overall_median


array([2., 5., 8.])

### In the context of NumPy arrays:

Axis 0 refers to the vertical axis (rows).
Axis 1 refers to the horizontal axis (columns)

### 3. `np.std()`
The `np.std()` function computes the standard deviation, which measures how spread out the numbers are from the mean. A lower value indicates that the data points are close to the mean, while a higher value indicates more spread.


In [123]:
arr = np.array([1, 2, 3, 4, 5])
std_value = np.std(arr)
std_value  # Output: 1.4142135623730951


np.float64(1.4142135623730951)

### `np.std()` for 2D Arrays
For a 2D array, `np.std()` computes the standard deviation, which can measure:

1. The overall spread of all elements.
2. The spread along a specified axis:
   - **axis=0**: Calculates standard deviation for each column.(vertical axis)
   - **axis=1**: Calculates standard deviation for each row. (horizontal axis)


In [124]:
overall_std = np.std(arr_2d)
overall_std  # Output: 2.581988897471611

np.float64(2.581988897471611)

In [125]:
column_std = np.std(arr_2d, axis=0)
column_std  # Output: [2.44948974 2.44948974 2.44948974]

array([2.44948974, 2.44948974, 2.44948974])

### 4. `np.sum()`
The `np.sum()` function returns the sum of all elements in the array. It can also sum along specific axes for multi-dimensional arrays.


In [126]:
arr = np.array([1, 2, 3, 4, 5])
sum_value = np.sum(arr)
sum_value  # Output: 15


np.int64(15)

### `np.sum()` for 2D Arrays
For a 2D array, `np.sum()` can calculate:

1. The total sum of all elements in the array.
2. The sum along a specific axis:
   - **axis=0**: Calculates the sum for each column.
   - **axis=1**: Calculates the sum for each row.


In [127]:
overall_sum = np.sum(arr_2d)
print(overall_sum)  # Output: 45


45


In [128]:
row_sum = np.sum(arr_2d, axis=1)
row_sum  # Output: [ 6 15 24]


array([ 6, 15, 24])