In [3]:
import numpy as np
my_arr=np.array([[3,35,68,56]],np.int8)
my_arr[0,2]

68

In [4]:
my_arr.shape

(1, 4)

In [5]:
my_arr.dtype

dtype('int8')

In [6]:
my_arr[0,2]=66
my_arr

array([[ 3, 35, 66, 56]], dtype=int8)

# NumPy Array Creation Methods

## Common methods:
1. From a list
2. Using `np.arange()`
3. Using `np.zeros()` or `np.ones()`
4. Using `np.linspace()`
5. Using `np.random.rand()`

**Bold text** and *italic text* are easy to create.

You can also add code snippets:
```python
import numpy as np
arr = np.array([1, 2, 3, 4])

# Creating a numpy aaray: Conversion from other python structures

In [7]:
list_array=np.array([[1,2,4],[2,4,2],[9,8,6]])
list_array

array([[1, 2, 4],
       [2, 4, 2],
       [9, 8, 6]])

In [8]:
list_array.dtype

dtype('int32')

In [9]:
list_array.shape

(3, 3)

In [10]:
list_array.size

9

In [11]:
np.array({34,24,23})

array({24, 34, 23}, dtype=object)

# Creating a numpy array- through Intrinsic Numpy array Creation Objects

In [12]:
zeros=np.zeros((2,3))

In [13]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [14]:
zeros.dtype

dtype('float64')

# creating numpy array: using np.arange

In [15]:
rng=np.arange(12)
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

# creating numpy array using np.linspace() 

In [16]:
lspace=np.linspace(1,5,12)
#ye mujhe 1 se le ke 5 tak equally linearly spaced 12 elements dega.
lspace

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

# creaating numpy array using np.empty()

In [17]:
emp=np.empty((3,3))
emp
#it gives empty array of 3*3 with random values.

array([[1.01855798e-312, 1.01855798e-312, 1.01855798e-312],
       [1.01855798e-312, 6.79038653e-313, 9.76118064e-313],
       [1.01855798e-312, 1.01855798e-312, 1.01855798e-312]])

In [18]:
empt_like=np.empty_like(lspace)
#takes array as an argument. what it does is:
# it returns a new array with the same shape and type as the input array (lspace),
# but without initializing its values, meaning the contents of the returned array are random.

empt_like


array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

# creating numpy array with np.identity()

In [19]:
ide=np.identity(10)
# returns an identity matrix of 10*10 , index starting from 0
ide

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [20]:
ide.shape

(10, 10)

In [21]:
ide.size

100

In [23]:
arr=np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [25]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [26]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [27]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [28]:
arr.shape

(25,)

# Numpy Axis

In [30]:
x=[[1,2,3],[4,5,6],[7,8,9]]
ar=np.array(x)
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [31]:
ar.sum(axis=0)
#axis 0 is along rows and axis 1 is along column
#in 1d there is not axis1 only axis0

array([12, 15, 18])

In [32]:
ar.sum(axis=1)

array([ 6, 15, 24])

# numpy attributes and methods

In [33]:
  #Transpose an array  

In [34]:
ar.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [35]:

for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
8
9


In [36]:
ar.ndim

2

In [39]:
ar.flatten()

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [40]:
ar.size

9

### Attributes are properties or characteristics of a NumPy object (usually an array). They store information about the object, such as its shape, size, data type, and so on. Attributes do not perform any actions; they simply hold data. They don't have parenthesis().

### where as Methods are functions associated with a NumPy object (like an array) that perform operations on that object. They can modify the object, return a new object, or perform calculations. Methods often take arguments and require parentheses for invocation

In [43]:
ar.nbytes 

36

In [46]:
ar.itemsize
#Size of numpy array= total no of elements in the array
#itemSize= memory used by each element
#nbytes=size * itemSize
#nbytes return the total memory size by array

4

In [48]:
one=np.array([1,3,5,6,88,6])
one

array([ 1,  3,  5,  6, 88,  6])

In [49]:
one.argmax()
#returns the index of the maximum element in the array.


4

In [50]:
ar.argmax()
#When you apply argmax to a multi-dimensional array without specifying an axis, it treats the array as a flattened array and returns the index of the maximum value in the entire array.

8

In [51]:
one.argmin()  
#return the index of minimum value

0

In [52]:
one.argsort()
# Returns the indices that would sort the array in ascending order.

array([0, 1, 2, 3, 5, 4], dtype=int64)

In [53]:
ar.argmin()

0

In [54]:
ar.argmax(axis=0)

array([2, 2, 2], dtype=int64)

In [55]:
ar.argmax(axis=1)

array([2, 2, 2], dtype=int64)