# Mathematical Operations in Numpy

In [18]:
import numpy as np

## Element-wise Operations

In [19]:
#Element-wise Addition
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
addition_result = a + b
addition_result


array([5, 7, 9])

In [20]:
# Element-wise Subtraction
subtraction_result = a - b
subtraction_result

array([-3, -3, -3])

In [21]:
#  Element-wise Multiplication
multiplication_result = a * b
multiplication_result

array([ 4, 10, 18])

In [22]:
#  Element-wise Division
division_result = a / b
division_result

array([0.25, 0.4 , 0.5 ])

In [23]:
# Element-wise Exponentiation
exponentiation_result = a ** 2
exponentiation_result

array([1, 4, 9])

## Universal Functions (ufuncs)
### 
### Radians and degrees are two units used to measure angles.

### Degrees:

#### A circle is divided into 360 equal parts, and each part is called a degree (°). So, one complete revolution around a circle is 360°.

### Radians:

#### A radian is based on the radius of a circle. It is the angle subtended by an arc whose length is equal to the radius of the circle. 
### There are 2π radians in a complete revolution around a circle.


## pi=180 degrees

### 1. Sine Function

In [24]:
# Sine Function
angles = np.array([0, np.pi/2, np.pi])
sine_result = np.sin(angles)
sine_result


array([0.0000000e+00, 1.0000000e+00, 1.2246468e-16])

### 2.Cos Function

In [25]:
#Cosine Function
cosine_result = np.cos(angles)
cosine_result


array([ 1.000000e+00,  6.123234e-17, -1.000000e+00])

### 3. Exponential Function
#### The exponential function is $e^x$, where e is Euler's number (approximately 2.71828), and x is the element of the array.

In [26]:
# Exponential Function
# numpy array a is defined at the start of this jupyter notebook.
exponential_result = np.exp(a)
exponential_result


array([ 2.71828183,  7.3890561 , 20.08553692])

### 4. Logarithm Function  np.log() function:
#### np.log() calculates the natural logarithm (logarithm base e) of each element in the input array. The natural logarithm of a number x is written as ln(x), and it is the inverse of the exponential function $𝑒^x$ .The logarithm of x, where 𝑥=0, is undefined because the natural logarithm of zero approaches negative infinity.

In [27]:
#Logarithm Function
logarithm_result = np.log(a)  # you can add 1 to avoid log(0)
logarithm_result


array([0.        , 0.69314718, 1.09861229])

## Linear Algebra Functions



### 1. Dot Product

#### np.dot(a, b) computes the dot product of arrays a and b.
#### If a and b are both 1D arrays, it performs the traditional dot product of vectors.
#### If a and b are both 2D arrays, it performs matrix multiplication.

In [28]:
#  Dot Product
dot_product_result = np.dot(a, b)
dot_product_result


np.int64(32)

### 2. Matrix Inversion

In [29]:
# Cell 12: Matrix Inversion
matrix = np.array([[1, 2], [3, 4]])
inverse_result = np.linalg.inv(matrix)
inverse_result


array([[-2. ,  1. ],
       [ 1.5, -0.5]])