#  Intro to Numpy-Video1

## Benefits of using NumPy over standard Python lists

####  NumPy Arrays use C-style static arrays, which means they are more memory efficient. In a NumPy array, the data is stored directly in contiguous blocks of memory, not references to objects. This is why NumPy arrays are faster for numerical operations: they avoid the overhead of handling references and can leverage low-level optimizations.

#### In contrast, Python lists are dynamic arrays. Every time the list grows beyond its current capacity, Python doubles the size of the array to accommodate more elements. Python lists are referential arrays, meaning they store references (or pointers) to the actual data, not the data itself. When you access an item in a Python list, you first retrieve the reference (or address) of the data and then access the actual data.

## Numpy Array vs Python List (Speed)

In [72]:
#running the code using python list
a=[i for i in range(100000000)]
b=[i for i in range(100000000,200000000)]
c=[]
import time
start = time.time()
for i in range (len(a)):
    c.append(a[i]+b[i])
print(time.time()-start)

21.640979766845703


In [73]:
#doing the same work with numpy array

import numpy as np
a=np.arange(100000000)
b=np.arange(100000000,200000000)
start=time.time()
c=a+b
print(time.time()-start)

1.338000774383545


##  Numpy Array vs Python List (Memory)

In [74]:
# in python lists
a=[i for i in range(10000000)]
import sys
sys.getsizeof(a)
#gives size in bytes

89095160

In [75]:
#in numpy arrays(we can reduce the total size by changing the dtype thus it will take less memory)
a= np.arange(10000000,dtype=np.int32)
sys.getsizeof(a)

40000112

# Numpy Creation Methods

1. From a list using `np.array()`
2. Using `np.arange()`
3. Using `np.zeros()` or `np.ones()`
4. Using `np.linspace()`
5. Using `np.random.rand()`

```python
import numpy as np
arr = np.array([1, 2, 3, 4])

## 1. Creating a numpy array: Conversion from other python structures

In [76]:
import numpy as np   
numpy_array=np.array([[1,2,4],[2,4,2],[9,8,6]])
numpy_array

array([[1, 2, 4],
       [2, 4, 2],
       [9, 8, 6]])

# Numpy Array Attributes

In [77]:
numpy_array.dtype

dtype('int64')

In [78]:
numpy_array.shape

(3, 3)

In [79]:
numpy_array.size

9

In [80]:
numpy_array.ndim

2

## 2. Creating a numpy array- through np.zeros and np.ones

In [81]:
zeros=np.zeros((2,3))

In [82]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [83]:
zeros.dtype

dtype('float64')

In [84]:
ones=np.ones((3,4),dtype=int)

In [85]:
ones

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [86]:
ones.dtype

dtype('int64')

## 3. creating numpy array: using np.arange

In [87]:
rng=np.arange(12)
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

## 4. creating numpy array using np.linspace() 

In [88]:
lspace=np.linspace(1,4,12)

In [89]:
#ye mujhe 1 se le ke 5 tak equally linearly spaced 12 elements dega.
lspace

array([1.        , 1.27272727, 1.54545455, 1.81818182, 2.09090909,
       2.36363636, 2.63636364, 2.90909091, 3.18181818, 3.45454545,
       3.72727273, 4.        ])

## 5. creaating numpy array using np.empty()

In [90]:
emp=np.empty((2,2))
emp
#it gives empty array of 3*3 with random values.

array([[0.0e+000, 4.9e-324],
       [9.9e-324, 1.5e-323]])

In [91]:
empty_like=np.empty_like(lspace)
#takes array as an argument. what it does is:
# it returns a new array with the same shape and type as the input array (lspace),
# but without initializing its values, meaning the contents of the returned array are random.

empty_like

array([1.        , 1.27272727, 1.54545455, 1.81818182, 2.09090909,
       2.36363636, 2.63636364, 2.90909091, 3.18181818, 3.45454545,
       3.72727273, 4.        ])

## 6. creating numpy array with np.identity()

In [92]:
ide=np.identity(5,dtype=int)
# returns an identity matrix of 5*5 , index starting from 0
ide

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])