# Mathematical Operations in Numpy

In [17]:
import numpy as np

## Element-wise Operations

In [18]:
# Cell 2: Element-wise Addition
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
addition_result = a + b
addition_result


array([5, 7, 9])

In [19]:
# Cell 3: Element-wise Subtraction
subtraction_result = a - b
subtraction_result

array([-3, -3, -3])

In [20]:
# Cell 4: Element-wise Multiplication
multiplication_result = a * b
multiplication_result

array([ 4, 10, 18])

In [21]:
# Cell 5: Element-wise Division
division_result = a / b
division_result

array([0.25, 0.4 , 0.5 ])

In [22]:
# Cell 6: Element-wise Exponentiation
exponentiation_result = a ** 2
exponentiation_result

array([1, 4, 9])

## Universal Functions (ufuncs)