# Numpy Array Manipulation- Video2


In [206]:
import numpy as np

# Reshaping Arrays: reshape(),ravel(), flatten()

In [207]:
#Reshaping Arrays
print("RESHAPING ARRAYS")

# Create a sample array
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

# reshape() 
reshaped = arr.reshape(3, 4)  # Reshape to 3x4 matrix
reshaped


RESHAPING ARRAYS


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [208]:
# ravel() - Flatten array to 1D (returns view when possible)
raveled = reshaped.ravel()
raveled

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [209]:
# flatten() - Flatten array to 1D (always returns copy)
flattened = reshaped.flatten()
flattened

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

## Difference between ravel() and flatten()
Memory Behavior:

ravel() returns a view of the original array when possible (memory efficient)
whereas flatten() always returns a copy of the array (new memory allocation)


Performance:

ravel() is generally faster since it doesn't copy data
whereas flatten() is slower since it always creates a copy


Use Cases:

Use ravel() when you want to modify the original array
whereas flatten() when you want to ensure the original array remains unchanged


Memory Layout:

ravel() may return a view or a copy depending on the array's memory layout
 whereas flatten() gives you control over the memory layout with order parameter ('C' for row-major, 'F' for column-major)
 
### note: 
The phrase "when possible" in the context of ravel() refers to the conditions under which NumPy can return a view of the original array instead of making a copy.

Conditions for Returning a View:
Contiguous Memory:

For ravel() to return a view, the original array must be stored in contiguous memory. This means that the data should be laid out in a continuous block of memory without any gaps.
Arrays that are created using certain slicing operations, or those that have been transposed (like switching rows and columns), may not be contiguous.
           
Array Structure:

If the array is a simple structure (e.g., created from a single call to np.array()), it's more likely to be contiguous and thus will allow ravel() to return a view.
If the array is multi-dimensional but not laid out in a straightforward manner, such as a non-contiguous view or an array created from other arrays that were not contiguous, ravel() will return a copy.

In [210]:
print("DIFFERENCE BETWEEN RAVEL() AND FLATTEN()")

# Using ravel()
raveled = arr.ravel()
print("\nAfter ravel():", raveled)

# Using flatten()
flattened = arr.flatten()
print("\nAfter flatten():", flattened)

# Key Difference: Memory Behavior
print("\nDEMONSTRATING MEMORY BEHAVIOR")
print("-" * 50)

# Modify raveled array
print("Original array before modification:\n", arr)
raveled[0] = 99
print("\nOriginal array after modifying raveled array:\n", arr)  # Original array changes

# Reset array
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

# Modify flattened array
flattened = arr.flatten()
flattened[0] = 99
print("\nOriginal array after modifying flattened array:\n", arr)  # Original array unchanged

DIFFERENCE BETWEEN RAVEL() AND FLATTEN()

After ravel(): [ 1  2  3  4  5  6  7  8  9 10 11 12]

After flatten(): [ 1  2  3  4  5  6  7  8  9 10 11 12]

DEMONSTRATING MEMORY BEHAVIOR
--------------------------------------------------
Original array before modification:
 [ 1  2  3  4  5  6  7  8  9 10 11 12]

Original array after modifying raveled array:
 [99  2  3  4  5  6  7  8  9 10 11 12]

Original array after modifying flattened array:
 [ 1  2  3  4  5  6  7  8  9 10 11 12]


#  Indexing and Slicing

In [211]:
print("INDEXING AND SLICING")
print("-" * 50)

# Create a 2D array
arr_2d = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]])
print("2D array:\n", arr_2d)


INDEXING AND SLICING
--------------------------------------------------
2D array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [212]:
# Basic indexing
print("\nElement at position (1,2):", arr_2d[1, 2])


Element at position (1,2): 7


In [213]:
# Slicing
print("\nFirst two rows, last two columns:\n", arr_2d[0:2, 2:4])


First two rows, last two columns:
 [[3 4]
 [7 8]]


In [214]:
# Boolean indexing
print("\nElements greater than 6:\n", arr_2d[arr_2d > 6])


Elements greater than 6:
 [ 7  8  9 10 11 12]


#  Broadcasting

In [215]:
print("BROADCASTING")
print("-" * 50)

# Create arrays of different shapes
arr1 = np.array([[1, 2, 3],
                 [4, 5, 6]])  # 2x3 array
arr2 = np.array([10, 20, 30])  # 1D array

# Broadcasting operation
result = arr1 + arr2  # arr2 is broadcast to match arr1's shape
result

BROADCASTING
--------------------------------------------------


array([[11, 22, 33],
       [14, 25, 36]])

# Array Concatenation and Splitting
 ## axis:
  ###  axis=0: Concatenates along the rows (vertically).
  ###  axis=1: Concatenates along the columns (horizontally).

In [216]:
print("ARRAY CONCATENATION AND SPLITTING")
print("-" * 50)

# Create arrays
arr1 = np.array([[1, 2], 
                 [3, 4]])
arr2 = np.array([[5, 6], 
                 [7, 8]])

# concatenate()
concat_horizontal = np.concatenate((arr1, arr2), axis=1)
print("Horizontal concatenation:\n", concat_horizontal)

ARRAY CONCATENATION AND SPLITTING
--------------------------------------------------
Horizontal concatenation:
 [[1 2 5 6]
 [3 4 7 8]]


In [217]:
# Stack them along a new axis
stacked = np.stack((arr1, arr2), axis=0)
stacked

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [218]:
# vstack() - Vertical stacking
vstacked = np.vstack((arr1, arr2))
vstacked

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [219]:
# hstack() - Horizontal stacking
hstacked = np.hstack((arr1, arr2))
hstacked

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

### note: For both stacking methods, the input arrays must have compatible dimensions:

#### For vertical stacking, the arrays must have the same number of columns.
#### For horizontal stacking, the arrays must have the same number of rows.

# Splitting Arrays

In [220]:
# Split horizontally into 4 parts
hsplit = np.hsplit(concat_horizontal, 4)

In [221]:
print("\nHorizontal split:")
print("First part:", hsplit[0])


Horizontal split:
First part: [[1]
 [3]]


In [222]:
print("Second part:\n", hsplit[1])

Second part:
 [[2]
 [4]]


In [223]:
print("Third part:\n", hsplit[2])

Third part:
 [[5]
 [7]]


In [224]:
print("Fourth part:\n", hsplit[3])

Fourth part:
 [[6]
 [8]]


# Combined Operations Example

In [225]:
print("COMBINED OPERATIONS EXAMPLE")
print("-" * 50)

# Create a complex array
complex_arr = np.arange(24).reshape(4, 6)
print("Original array:\n", complex_arr)



COMBINED OPERATIONS EXAMPLE
--------------------------------------------------
Original array:
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [226]:
# Split into three parts horizontally
splits = np.hsplit(complex_arr, 3)
splits

[array([[ 0,  1],
        [ 6,  7],
        [12, 13],
        [18, 19]]),
 array([[ 2,  3],
        [ 8,  9],
        [14, 15],
        [20, 21]]),
 array([[ 4,  5],
        [10, 11],
        [16, 17],
        [22, 23]])]

In [227]:
# Perform operations on each split
processed_splits = [split * 2 for split in splits]
processed_splits

[array([[ 0,  2],
        [12, 14],
        [24, 26],
        [36, 38]]),
 array([[ 4,  6],
        [16, 18],
        [28, 30],
        [40, 42]]),
 array([[ 8, 10],
        [20, 22],
        [32, 34],
        [44, 46]])]

In [228]:
# Stack them vertically
final_result = np.vstack(processed_splits)
print("\nFinal result after splitting, processing, and stacking:\n", final_result)


Final result after splitting, processing, and stacking:
 [[ 0  2]
 [12 14]
 [24 26]
 [36 38]
 [ 4  6]
 [16 18]
 [28 30]
 [40 42]
 [ 8 10]
 [20 22]
 [32 34]
 [44 46]]
