In [17]:
import numpy as np
my_arr=np.array([[3,35,68,56]],np.int8)
my_arr[0,2]

68


(1, 4)

In [18]:
my_arr.shape

(1, 4)

In [19]:
my_arr.dtype

dtype('int8')

In [22]:
my_arr[0,2]=66
my_arr

array([[ 3, 35, 66, 56]], dtype=int8)

# NumPy Array Creation Methods

## Common methods:
1. From a list
2. Using `np.arange()`
3. Using `np.zeros()` or `np.ones()`
4. Using `np.linspace()`
5. Using `np.random.rand()`

**Bold text** and *italic text* are easy to create.

You can also add code snippets:
```python
import numpy as np
arr = np.array([1, 2, 3, 4])

# Creating a numpy aaray: Conversion from other python structures

In [24]:
list_array=np.array([[1,2,4],[2,4,2],[9,8,6]])
list_array

array([[1, 2, 4],
       [2, 4, 2],
       [9, 8, 6]])

In [25]:
list_array.dtype

dtype('int32')

In [26]:
list_array.shape

(3, 3)

In [27]:
list_array.size

9

In [28]:
np.array({34,24,23})

array({24, 34, 23}, dtype=object)

# Creating a numpy array- through Intrinsic Numpy array Creation Objects

In [33]:
zeros=np.zeros((2,3))

In [34]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [35]:
zeros.dtype

dtype('float64')