#  Intro to Numpy-Video1

## Benefits of using NumPy over standard Python lists

####  NumPy Arrays use C-style static arrays, which means they are more memory efficient. In a NumPy array, the data is stored directly in contiguous blocks of memory, not references to objects. This is why NumPy arrays are faster for numerical operations: they avoid the overhead of handling references and can leverage low-level optimizations.

#### In contrast, Python lists are dynamic arrays. Every time the list grows beyond its current capacity, Python doubles the size of the array to accommodate more elements. Python lists are referential arrays, meaning they store references (or pointers) to the actual data, not the data itself. When you access an item in a Python list, you first retrieve the reference (or address) of the data and then access the actual data.

## Numpy Array vs Python List (Speed)

In [141]:
#running the code using python list
a=[i for i in range(100000000)]
b=[i for i in range(100000000,200000000)]
c=[]
import time
start = time.time()
for i in range (len(a)):
    c.append(a[i]+b[i])
print(time.time()-start)

25.306196928024292


In [142]:
#doing the same work with numpy array

import numpy as np
a=np.arange(100000000)
b=np.arange(100000000,200000000)
start=time.time()
c=a+b
print(time.time()-start)

2.259840965270996


##  Numpy Array vs Python List (Memory)

In [143]:
# in python lists
a=[i for i in range(10000000)]
import sys
sys.getsizeof(a)
#gives size in bytes

89095160

In [144]:
#in numpy arrays(we can reduce the total size by changing the dtype thus it will take less memory)
a= np.arange(10000000,dtype=np.int32)
sys.getsizeof(a)

40000112

# Numpy Array vs Python Array Comparison(Speed)
### Note: Python does not have built-in support for Arrays, but Python Lists can be used instead.

#### Python includes an array module that provides a more efficient way to store homogeneous data types (all elements of the same type). However, it is less commonly used than lists.
#### Note: List can store heterogeneous data

#### In the below example, you can see that numpy array speed is almost 65 times than python array. this is not concrete but a rough estimation of how speed of numpy array is much more significant as compared with python array.


In [145]:
from array import array

In [146]:
# Define the size of the array
size = 10_000_000

# Creating a Python array with integers
python_array = array('i', range(size))

# Creating a NumPy array with integers
numpy_array = np.arange(size)


In [147]:
# Function to multiply each element by 2 in a Python array
def multiply_python_array(arr):
    for i in range(len(arr)):
        arr[i] = arr[i] * 2

# Function to multiply each element by 2 in a NumPy array
def multiply_numpy_array(arr):
    arr *= 2

In [148]:
# Measuring time for Python array
start_time = time.time()
multiply_python_array(python_array)
python_time = time.time() - start_time
f"time consumed by python array: {python_time:.6f}"


'time consumed by python array: 1.218110'

In [149]:
# Measuring time for NumPy array
start_time = time.time()
multiply_numpy_array(numpy_array)
numpy_time = time.time() - start_time
f"time consumed by numpy array: {numpy_time:.6f}"


'time consumed by numpy array: 0.011012'

# Numpy vs Python Array Module Memory Consumption Comparison

#### The primary advantage of NumPy over the Python array module is functionality, not basic memory efficiency as no such significant differences can be observed But in some cases it can vary but that is not the significant point here. :
### Functionalities: 
#### NumPy supports multi-dimensional arrays (matrices, tensors).
#### It offers a vast array of operations and mathematical functions optimized for performance.
#### It supports different data types and broadcasting capabilities that the basic array module does not

In [150]:
# Getting the memory usage of the Python array
python_array_memory = sys.getsizeof(python_array) + (python_array.itemsize * len(python_array))
f"Memory usage for Python array: {python_array_memory / (1024 ** 2):.2f} MB"


'Memory usage for Python array: 77.22 MB'

In [151]:
# Getting the memory usage of the NumPy array
numpy_array_memory = numpy_array.nbytes
f"Memory usage for NumPy array: {numpy_array_memory / (1024 ** 2):.2f} MB"


'Memory usage for NumPy array: 76.29 MB'

# Numpy Creation Methods

1. From a list using `np.array()`
2. Using `np.arange()`
3. Using `np.zeros()` or `np.ones()`
4. Using `np.linspace()`
5. Using `np.random.rand()`

```python
import numpy as np
arr = np.array([1, 2, 3, 4])

## 1. Creating a numpy array: Conversion from other python structures

In [152]:
import numpy as np   
numpy_array=np.array([[1,2,4],[2,4,2],[9,8,6]])
numpy_array

array([[1, 2, 4],
       [2, 4, 2],
       [9, 8, 6]])

# Numpy Array Attributes

In [153]:
numpy_array.dtype

dtype('int64')

In [154]:
numpy_array.shape

(3, 3)

In [155]:
numpy_array.size

9

In [156]:
numpy_array.ndim

2

## 2. Creating a numpy array- through np.zeros and np.ones

In [157]:
zeros=np.zeros((2,3))

In [158]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [159]:
zeros.dtype

dtype('float64')

In [160]:
ones=np.ones((3,4),dtype=int)

In [161]:
ones

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [162]:
ones.dtype

dtype('int64')

## 3. creating numpy array: using np.arange

In [163]:
rng=np.arange(12)
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

## 4. creating numpy array using np.linspace() 

In [164]:
lspace=np.linspace(1,4,12)

In [165]:
#ye mujhe 1 se le ke 5 tak equally linearly spaced 12 elements dega.
lspace

array([1.        , 1.27272727, 1.54545455, 1.81818182, 2.09090909,
       2.36363636, 2.63636364, 2.90909091, 3.18181818, 3.45454545,
       3.72727273, 4.        ])

## 5. creaating numpy array using np.empty()

In [166]:
emp=np.empty((2,2))
emp
#it gives empty array of 3*3 with random values.

array([[0.0e+000, 4.9e-324],
       [9.9e-324, 1.5e-323]])

In [167]:
empty_like=np.empty_like(lspace)
#takes array as an argument. what it does is:
# it returns a new array with the same shape and type as the input array (lspace),
# but without initializing its values, meaning the contents of the returned array are random.

empty_like

array([1.        , 1.27272727, 1.54545455, 1.81818182, 2.09090909,
       2.36363636, 2.63636364, 2.90909091, 3.18181818, 3.45454545,
       3.72727273, 4.        ])

## 6. creating numpy array with np.identity()

In [168]:
ide=np.identity(5,dtype=int)
# returns an identity matrix of 5*5 , index starting from 0
ide

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])